language: node_js
node_js: 9.0.0
dist: trusty
sudo: required
branches:
  only:
    - master
    - develop

cache:
  directories: SimpleApp/node_modules

before_install:
  cd SimpleApp

before_script:
  - npm install -g @angular/cli

script:
  - ng build --aot

deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_KEY_USER_PABLOIN
    app:
      master: cicd-simple-app
      develop: cicd-simple-app-dev
    on:
      repo: Pabloin/CI-CD-app-Angular-Travis-Heroku


notifications:
  slack: devops-arg:4pqehU7DgM2Vvrcyfu52j6Pc



# Slack Notifications:
#       Based on: https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications

  # slack:
  #   rooms:
  #     - <account>:<token>#development
  #     - <account>:<token>#general

  # notifications:
  #   slack: '<account>:<token>#development'

# https://docs.travis-ci.com/user/customizing-the-build/
# Travis build lifecycle, including three optional deployment steps

  # OPTIONAL Install apt addons
  # OPTIONAL Install cache components
  # before_install
  # install
  # before_script
  # script
  # OPTIONAL before_cache (for cleaning up cache)
  # after_success or after_failure
  # OPTIONAL before_deploy
  # OPTIONAL deploy
  # OPTIONAL after_deploy
  # after_script


# About Chrome Setup
#  https://gist.github.com/AhsanAyaz/820d40da5d1aa45c138f9e55d5193d34
#  You can avoid all the setup by using Travis' Chrome addon and their provided xvfb-run wrapper.
    #  addons:
    #   chrome: stable

    #  script:
    #   - npm run lint
    #   - npm run test:headless
    #   - npm run build
    #   - xvfb-run npm run e2e


# Para Firebase Hosting
#   https://medium.com/@jamzi/continuous-everything-with-angular-travis-ci-firebase-and-greenkeeper-6656543bd826

    # before_script:
    #    - npm install -g firebase-tools
    #    - npm install -g @angular/cli

    # script:
    #    - ng build --prod --aot

    # after_success:
    #    - firebase deploy --token $FIREBASE_TOKEN


# Secure Environment Variables With Travis CI
#   https://brettdewoody.com/secure-environment-variables-with-travis/
# gem install travis
# travis encrypt DB_URL=super_secret
# travis encrypt DB_URL=super_secret --add env